# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ta20160927_cocoapod_sqlite' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
   use_frameworks!

  # Pods for ta20160927_cocoapod_sqlite
  pod 'SQLite.swift', '~> 0.10.1'

end
