# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ta20160928_alamofire' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ta20160928_alamofire
  pod 'Alamofire', '3.4.2'
  pod 'AlamofireImage', '2.3.1'

end
